export type OfferLanguage = "pl" | "en";

type OfferContent = {
  title: string;
  location: string;
  type: string;
  bedrooms: string;
  area: string;
  price: string;
  description: string[];
};

export type OfferView = OfferContent & {
  id: string;
  shareId: string;
  mainImage: string;
  images: string[];
};

type Offer = {
  id: string;
  shareId: string;
  mainImage: string;
  images: string[];
  content: Record<OfferLanguage, OfferContent>;
};

const offers: Offer[] = [
  {
    id: "offer-1",
    shareId: "offer-chloraka-apartments-villas",
    mainImage: "/images/offers/offer-1/main2.jpg",
    images: [
      "/images/offers/offer-1/main2.jpg",
      "/images/offers/offer-1/1.jpg",
      "/images/offers/offer-1/2.jpg",
      "/images/offers/offer-1/3.jpg",
      "/images/offers/offer-1/4-v2.jpg",
      "/images/offers/offer-1/5.jpg",
      "/images/offers/offer-1/6.jpg",
      "/images/offers/offer-1/7.jpg",
      "/images/offers/offer-1/8.jpg",
      "/images/offers/offer-1/9.jpg",
      "/images/offers/offer-1/10.jpg",
    ],
    content: {
      pl: {
        title: "Apartamenty i wille w Chlorace",
        location: "Pafos, Chloraka",
        type: "Apartament / Willa",
        bedrooms: "2 / 3",
        area: "83 m² / 140 m²",
        price: "Od 285 000 €",
        description: [
          "Apartamenty 2-pokojowe 83 m² + 10 m² taras w cenie od 285 000 Euro.",
          "Wille 3-pokojowe 140 m² + 10 m² taras + 250 m² działka w cenie od 410 000 Euro.",
          "CHLORAKA",
          "Miejscowość Chloraka położona jest na zachód od dystryktu Pafos, około 3 kilometry od centrum miasta.",
          "Dolna Chloraka jest uznawana za jedną z najbardziej pożądanych lokalizacji w Pafos, zarówno do stałego zamieszkania, jak i pod wynajem krótkoterminowy.",
          "W miejscowości znajduje się wiele hoteli położonych przy wybrzeżu, restauracji, barów oraz atrakcji rekreacyjnych.",
          "Położona jest na średniej wysokości około 70 metrów nad poziomem morza, oferując wspaniałe widoki na Morze Śródziemne.",
          "Chloraka graniczy z miejscowościami Emba, Lemba i Kissonerga.",
          "To wyjątkowe miejsce z pięknymi plażami, harmonijnie łączące tradycyjną i nowoczesną zabudowę z zachwycającym naturalnym otoczeniem.",
          "Zamknięte osiedle składające się z 12 dwukondygnacyjnych domów z 3 sypialniami oraz 8 apartamentów z 2 sypialniami.",
          "Opcjonalnie dostępny jest prywatny basen oraz ogród na dachu, które dodają odrobinę luksusu do spokojnego otoczenia.",
          "Nowoczesna koncepcja architektoniczna harmonijnie łączy inwestycję z naturalnym środowiskiem, tworząc przestronne i funkcjonalne wnętrza.",
          "Naturalny krajobraz otacza osiedle, zapewniając prywatność i spokój, bez rezygnacji z wygody — wszystkie niezbędne udogodnienia znajdują się zaledwie 2 minuty od inwestycji.",
          "Niezależnie od tego, czy szukasz atrakcyjnej inwestycji, czy własnego miejsca do zamieszkania, ta inwestycja jest idealnym wyborem.",
        ],
      },
      en: {
        title: "Apartments and Villas in Chloraka",
        location: "Paphos, Chloraka",
        type: "Apartment / Villa",
        bedrooms: "2 / 3",
        area: "83 m² / 140 m²",
        price: "From €285,000",
        description: [
          "2-bedroom apartments of 83 m² + 10 m² terrace from €285,000.",
          "3-bedroom villas of 140 m² + 10 m² terrace + 250 m² plot from €410,000.",
          "CHLORAKA",
          "Chloraka is located west of the Paphos district, approximately 3 kilometres from the city centre.",
          "Lower Chloraka is considered one of the most desirable locations in Paphos, both for permanent living and short-term rental investment.",
          "The area offers many seafront hotels, restaurants, bars and leisure attractions.",
          "Situated at an average elevation of around 70 metres above sea level, Chloraka offers beautiful views of the Mediterranean Sea.",
          "Chloraka borders Emba, Lemba and Kissonerga.",
          "It is a unique location with beautiful beaches, combining traditional and modern architecture with an impressive natural setting.",
          "This gated development consists of 12 two-storey 3-bedroom houses and 8 two-bedroom apartments.",
          "A private pool and roof garden are optionally available, adding a touch of luxury to the peaceful surroundings.",
          "The modern architectural concept blends harmoniously with the natural environment, creating spacious and functional interiors.",
          "The natural landscape surrounds the development, offering privacy and tranquillity without sacrificing convenience — all essential amenities are just 2 minutes away.",
          "Whether you are looking for an attractive investment or your own place to live, this development is an ideal choice.",
        ],
      },
    },
  },
  {
    id: "offer-2",
    shareId: "offer-kissonerga-villas-sea",
    mainImage: "/images/offers/offer-2/main3.jpg",
    images: [
      "/images/offers/offer-2/main3.jpg",
      "/images/offers/offer-2/1.jpg",
      "/images/offers/offer-2/2.jpg",
      "/images/offers/offer-2/3.jpg",
      "/images/offers/offer-2/4.jpg",
      "/images/offers/offer-2/5-v2.jpg",
      "/images/offers/offer-2/6.jpg",
      "/images/offers/offer-2/7.jpg",
      "/images/offers/offer-2/8.jpg",
      "/images/offers/offer-2/9.jpg",
    ],
    content: {
      pl: {
        title: "Wille w doskonałej lokalizacji, 400 m od morza",
        location: "Kissonerga, Chloraka",
        type: "Willa",
        bedrooms: "3",
        area: "121 m²",
        price: "Od 480 000 €",
        description: [
          "Wille 3-pokojowe 121 m² + 15 m² taras + działka od 185 m² w cenie od 480 000 Euro.",
          "KISSONERGA",
          "Kissonerga to urokliwa miejscowość położona na słonecznym wybrzeżu Cypru, oferująca wyjątkowe połączenie atrakcji zarówno dla turystów, jak i mieszkańców.",
          "Słynie z pięknych plaż, idealnych do wypoczynku i aktywności wodnych. Złocisty piasek oraz krystalicznie czysta woda sprawiają, że jest to doskonałe miejsce do opalania, pływania i uprawiania sportów wodnych.",
          "Można tu również odkrywać lokalne restauracje i tawerny, serwujące szeroki wybór dań kuchni śródziemnomorskiej.",
          "Kissonerga jest miejscem stworzonym zarówno dla osób poszukujących spokojnego wypoczynku, jak i dla tych, którzy chcą stać się częścią tętniącej życiem społeczności.",
          "Niezależnie od tego, czy marzysz o spokojnym miejscu do relaksu, czy aktywnym życiu towarzyskim, Kissonerga oferuje idealne połączenie atrakcji wakacyjnych i komfortowych warunków do stałego zamieszkania.",
          "Kissonerga to doskonały kierunek dla każdego, kto chce cieszyć się pięknem Cypru, poznawać jego bogatą historię i kulturę oraz delektować się wyśmienitą lokalną kuchnią.",
          "Ta ekskluzywna kolekcja 4 dwukondygnacyjnych domów oferuje eleganckie rezydencje z 3 sypialniami i 3 łazienkami, zaprojektowane z myślą o nowoczesnym komforcie i wygodnym stylu życia.",
          "Każdy dom jest w pełni wyposażony, a cena obejmuje prywatny basen, klimatyzację typu split, wysokiej jakości sprzęt AGD, wbudowane miejsce do grillowania BBQ, instalację fotowoltaiczną o mocy 5 kW, bramę wjazdową, system alarmowy oraz przygotowanie pod centralne ogrzewanie — łącząc funkcjonalność, energooszczędność i elegancki design.",
          "Położone w prestiżowej lokalizacji domy oferują niezakłócone widoki na Pafos i Morze Śródziemne, a jednocześnie znajdują się zaledwie 2 minuty od centrum miejscowości, zapewniając łatwy dostęp do lokalnych udogodnień bez utraty spokoju i prywatności.",
          "Niezależnie od tego, czy szukasz bezpiecznej inwestycji, czy prywatnego śródziemnomorskiego azylu, ta inwestycja oferuje harmonijny styl życia w jednym z najbardziej malowniczych i spokojnych zakątków Cypru.",
        ],
      },
      en: {
        title: "Villas in an Excellent Location, 400 m from the Sea",
        location: "Kissonerga, Chloraka",
        type: "Villa",
        bedrooms: "3",
        area: "121 m²",
        price: "From €480,000",
        description: [
          "3-bedroom villas of 121 m² + 15 m² terrace + plot from 185 m² from €480,000.",
          "KISSONERGA",
          "Kissonerga is a charming village located on the sunny coast of Cyprus, offering a unique combination of attractions for both visitors and residents.",
          "It is known for its beautiful beaches, ideal for relaxation and water activities. Golden sand and crystal-clear water make it an excellent place for sunbathing, swimming and water sports.",
          "You can also discover local restaurants and tavernas serving a wide selection of Mediterranean cuisine.",
          "Kissonerga is ideal both for those looking for a peaceful retreat and for those who want to become part of a lively local community.",
          "Whether you dream of a calm place to relax or an active social lifestyle, Kissonerga offers the perfect blend of holiday atmosphere and comfortable conditions for permanent living.",
          "Kissonerga is an excellent destination for anyone who wants to enjoy the beauty of Cyprus, explore its rich history and culture, and enjoy outstanding local cuisine.",
          "This exclusive collection of 4 two-storey homes offers elegant 3-bedroom, 3-bathroom residences designed for modern comfort and convenient living.",
          "Each home is fully equipped, and the price includes a private swimming pool, split-unit air conditioning, high-quality electrical appliances, a built-in BBQ area, a 5 kW photovoltaic system, entrance gate, alarm system and provision for central heating — combining functionality, energy efficiency and elegant design.",
          "Located in a prestigious setting, the homes offer uninterrupted views of Paphos and the Mediterranean Sea, while being just 2 minutes from the village centre, providing easy access to local amenities without sacrificing peace and privacy.",
          "Whether you are looking for a secure investment or a private Mediterranean retreat, this development offers a harmonious lifestyle in one of Cyprus’s most scenic and peaceful locations.",
        ],
      },
    },
  },
  {
    id: "offer-3",
    shareId: "offer-emba-modern-development",
    mainImage: "/images/offers/offer-3/main-v2.png",
    images: [
      "/images/offers/offer-3/main-v2.png",
      "/images/offers/offer-3/1.png",
      "/images/offers/offer-3/2.png",
      "/images/offers/offer-3/3.png",
      "/images/offers/offer-3/4.png",
      "/images/offers/offer-3/5-v2.png",
    ],
    content: {
      pl: {
        title: "Nowoczesny projekt willi i apartamentów",
        location: "Pafos, Emba",
        type: "Studio",
        bedrooms: "1",
        area: "41 m²",
        price: "Od 205 000 €",
        description: [
          "W projekcie dostępne są studia, mieszkania jedno- i dwupokojowe w cenie od 205 000 Euro oraz wille 3-pokojowe w cenie od 495 000 Euro.",
          "Kompleks wprowadza nowy standard nowoczesnej zabudowy mieszkaniowej w miejscowości Emba, łącząc odważną architekturę z miejskim stylem życia.",
          "Inwestycja położona jest przy głównej drodze w Emba, jednak została usytuowana w lekkim oddaleniu od ruchu ulicznego, dzięki czemu zapewnia wygodę życia blisko miasta, zachowując jednocześnie spokojne i komfortowe otoczenie.",
          "Charakterystyczne elewacje z betonu architektonicznego oraz dekoracyjne ceglane przesłony nadają projektowi wyjątkową i rozpoznawalną tożsamość wizualną.",
          "Kompleks obejmuje 36 nowoczesnych domów oraz dwa identyczne budynki apartamentowe, mieszczące łącznie 32 lokale mieszkalne, w tym apartamenty z jedną i dwiema sypialniami oraz studia.",
          "Siedem domów oferuje dodatkowy luksus w postaci prywatnego basenu. W centralnej części inwestycji znajduje się duży basen dla mieszkańców oraz osobny basen dla dzieci.",
          "Komfort codziennego życia podnoszą starannie zaprojektowane przestrzenie wspólne, obejmujące recepcję, eleganckie lobby oraz strefę wypoczynkową.",
          "Na poziomie podziemnym znajduje się nowoczesna siłownia, wspierająca aktywny i zrównoważony styl życia mieszkańców.",
          "Projekt wyróżnia się również strategiczną lokalizacją w pobliżu planowanego Metropolitan Private Hospital — nowoczesnego prywatnego szpitala, który ma powstać w Pafos.",
          "Dzięki temu mieszkańcy będą mieli łatwy dostęp do światowej klasy opieki medycznej tuż obok swojego miejsca zamieszkania.",
          "Ta inwestycja to starannie zaprojektowana społeczność mieszkaniowa, położona w jednej z najbardziej atrakcyjnych i dogodnych lokalizacji regionu Pafos, łącząca nowoczesną architekturę, wysoki standard życia oraz codzienną wygodę.",
        ],
      },
      en: {
        title: "Modern Development of Villas and Apartments",
        location: "Paphos, Emba",
        type: "Studio",
        bedrooms: "1",
        area: "41 m²",
        price: "From €205,000",
        description: [
          "The project offers studios, one- and two-bedroom apartments from €205,000, as well as 3-bedroom villas from €495,000.",
          "The complex introduces a new standard of modern residential development in Emba, combining bold architecture with an urban lifestyle.",
          "The development is located near the main road in Emba, but set slightly back from traffic, offering the convenience of living close to the city while maintaining a calm and comfortable environment.",
          "Distinctive architectural concrete façades and decorative brick screens give the project a unique and recognisable visual identity.",
          "The complex includes 36 modern homes and two identical apartment buildings, comprising a total of 32 residential units, including studios, one-bedroom and two-bedroom apartments.",
          "Seven homes offer the added luxury of a private swimming pool. A large communal pool and a separate children’s pool are located at the centre of the development.",
          "Carefully designed shared areas enhance everyday comfort, including a reception, elegant lobby and lounge area.",
          "On the underground level, there is a modern gym supporting an active and balanced lifestyle for residents.",
          "The project also benefits from a strategic location near the planned Metropolitan Private Hospital — a modern private hospital planned for Paphos.",
          "This will give residents easy access to world-class medical care close to their home.",
          "This development is a carefully designed residential community in one of the most attractive and convenient locations in the Paphos region, combining modern architecture, high living standards and everyday convenience.",
        ],
      },
    },
  },
  {
    id: "offer-4",
    shareId: "offer-tomb-of-the-kings-apartments",
    mainImage: "/images/offers/offer-4/main-v2.jpg",
    images: [
      "/images/offers/offer-4/main-v2.jpg",
      "/images/offers/offer-4/1.jpg",
      "/images/offers/offer-4/2-v2.jpg",
      "/images/offers/offer-4/3.jpg",
      "/images/offers/offer-4/4.jpg",
    ],
    content: {
      pl: {
        title: "Luksusowy styl życia w samym sercu Pafos",
        location: "Pafos, Tomb of the Kings",
        type: "Apartament",
        bedrooms: "1",
        area: "51 m²",
        price: "Od 311 000 €",
        description: [
          "Ceny apartamentów jednopokojowych zaczynają się od 311 000 Euro, dwupokojowych od 463 000 Euro, trzypokojowych od 611 000 Euro.",
          "Ten projekt to prestiżowy, nowo powstający kompleks mieszkaniowy w Pafos na Cyprze.",
          "Inwestycja realizowana jest na działce o powierzchni 9 100 m² i będzie składać się z pięciu niezależnych budynków.",
          "Projekt obejmuje 72 luksusowe apartamenty, wykończone zgodnie z najwyższymi standardami jakości.",
          "Kompleks będzie osiedlem zamkniętym, zapewniającym mieszkańcom wysoki poziom bezpieczeństwa, prywatności i ekskluzywności.",
          "Mieszkańcy będą mogli korzystać z szerokiej gamy udogodnień premium, takich jak strefa SPA, nowoczesna siłownia, eleganckie lobby, usługi concierge oraz całodobowa ochrona.",
          "Do dyspozycji mieszkańców oddany zostanie również duży wspólny basen, osobny basen dla dzieci, bar przy basenie oraz komfortowe strefy wypoczynkowe, idealne do relaksu i spędzania czasu wolnego.",
          "Inwestycja oferuje także starannie zaprojektowane tereny zielone, place zabaw dla dzieci oraz ogólnodostępne przestrzenie rekreacyjne z zagospodarowaną zielenią.",
          "Położony w doskonałej lokalizacji, tuż obok słynnego stanowiska archeologicznego Grobowce Królewskie (Tombs of the Kings), kompleks należy do największych projektów mieszkaniowych w regionie Pafos.",
          "Okolica zapewnia szybki i wygodny dostęp do wszystkich niezbędnych udogodnień, takich jak sklepy, restauracje, kawiarnie oraz środki transportu.",
          "Lokalizacja oraz koncepcja projektu zostały starannie przemyślane, aby zapewnić mieszkańcom najwyższy komfort życia, nowoczesne rozwiązania oraz luksusowe udogodnienia.",
          "Dzięki połączeniu prestiżowej lokalizacji, wysokiej jakości wykonania i bogatej infrastruktury rekreacyjnej, stanowi to doskonały wybór zarówno dla osób poszukujących luksusowego miejsca do życia, jak i dla inwestorów zainteresowanych atrakcyjną lokatą kapitału na rynku nieruchomości.",
        ],
      },
      en: {
        title: "Luxury Living in the Heart of Paphos",
        location: "Paphos, Tomb of the Kings",
        type: "Apartment",
        bedrooms: "1",
        area: "51 m²",
        price: "From €311,000",
        description: [
          "Prices for one-bedroom apartments start from €311,000, two-bedroom apartments from €463,000, and three-bedroom apartments from €611,000.",
          "This project is a prestigious new residential complex in Paphos, Cyprus.",
          "The development is being built on a 9,100 m² plot and will consist of five independent buildings.",
          "The project includes 72 luxury apartments finished to the highest quality standards.",
          "The complex will be a gated community, offering residents a high level of security, privacy and exclusivity.",
          "Residents will enjoy a wide range of premium amenities, including a spa area, modern gym, elegant lobby, concierge services and 24-hour security.",
          "A large communal swimming pool, separate children’s pool, pool bar and comfortable lounge areas will also be available for residents, ideal for relaxation and leisure.",
          "The development also includes carefully designed landscaped areas, children’s playgrounds and shared recreational spaces with greenery.",
          "Located in an excellent setting next to the famous Tombs of the Kings archaeological site, the complex is one of the largest residential projects in the Paphos region.",
          "The surrounding area offers quick and convenient access to all essential amenities, including shops, restaurants, cafés and transport links.",
          "The location and concept of the project have been carefully considered to provide residents with maximum comfort, modern solutions and luxury amenities.",
          "Combining a prestigious location, high-quality construction and rich recreational infrastructure, this development is an excellent choice both for those seeking a luxury place to live and for investors looking for an attractive real estate opportunity.",
        ],
      },
    },
  },
  {
    id: "offer-5",
    shareId: "offer-paphos-city-center-apartments",
    mainImage: "/images/offers/offer-5/main.png",
    images: [
      "/images/offers/offer-5/main.png",
      "/images/offers/offer-5/1.png",
      "/images/offers/offer-5/2.png",
      "/images/offers/offer-5/3.png",
      "/images/offers/offer-5/4.jpg",
      "/images/offers/offer-5/5.jpg",
      "/images/offers/offer-5/6.jpg",
    ],
    content: {
      pl: {
        title: "Architektura przyszłości w sercu Pafos",
        location: "Pafos, City Center",
        type: "Apartament",
        bedrooms: "1",
        area: "42 m²",
        price: "Od 220 800 €",
        description: [
          "Cena apartamentów jednopokojowych zaczyna się od 220 800 Euro, dwupokojowych od 429 000 Euro, trzypokojowych od 515 000 Euro.",
          "Położona w samym sercu miasta Pafos, ta wyjątkowa inwestycja znajduje się w otoczeniu najważniejszych punktów miejskiej infrastruktury, takich jak ratusz, kościoły, supermarkety, szkoły, szpitale, tereny miejskie oraz parki.",
          "Projekt zachwyca swoją dynamiczną, skręcającą formą, przypominającą chińskiego smoka unoszącego się na niebie.",
          "Jednocześnie budynek wyróżnia się licznymi futurystycznymi elementami architektonicznymi, odzwierciedlającymi ideę inteligentnego budynku przyszłości.",
          "Dzięki swojej wyjątkowej formie staje się nową ikoną i symbolem miasta.",
          "To miejsce, w którym spotykają się przeszłość i przyszłość.",
          "W przeszłości było to centrum miejskiego życia — tętniące energią, pełne mieszkańców i korzystające z wyjątkowych walorów lokalizacyjnych.",
          "W przyszłości stanie się jednym z najbardziej rozpoznawalnych punktów miasta, symbolem nowoczesności i nieograniczonych możliwości.",
          "Dynamiczne linie oraz eleganckie, płynne krzywizny sprawiają, że budynek wyraźnie wyróżnia się na tle otaczającej zabudowy, podkreślając swoją wyjątkową obecność i prestiżowy charakter.",
          "Ta inwestycja stanowi nowoczesną wizję miejskiego życia, łącząc innowacyjną architekturę, doskonałą lokalizację oraz najwyższy standard komfortu w samym centrum Pafos.",
        ],
      },
      en: {
        title: "Architecture of the Future in the Heart of Paphos",
        location: "Paphos, City Center",
        type: "Apartment",
        bedrooms: "1",
        area: "42 m²",
        price: "From €220,800",
        description: [
          "Prices for one-bedroom apartments start from €220,800, two-bedroom apartments from €429,000, and three-bedroom apartments from €515,000.",
          "Located in the very heart of Paphos, this unique development is surrounded by the city’s key infrastructure, including the town hall, churches, supermarkets, schools, hospitals, municipal areas and parks.",
          "The project impresses with its dynamic twisting form, reminiscent of a Chinese dragon rising into the sky.",
          "At the same time, the building features numerous futuristic architectural elements, reflecting the idea of an intelligent building of the future.",
          "Thanks to its distinctive form, it becomes a new icon and symbol of the city.",
          "This is a place where past and future meet.",
          "In the past, this was the centre of urban life — full of energy, residents and the benefits of an exceptional location.",
          "In the future, it will become one of the most recognisable landmarks in the city, a symbol of modernity and unlimited possibilities.",
          "Dynamic lines and elegant flowing curves make the building clearly stand out from its surroundings, emphasising its unique presence and prestigious character.",
          "This development represents a modern vision of urban living, combining innovative architecture, an excellent location and the highest standard of comfort in the very centre of Paphos.",
        ],
      },
    },
  },
  {
    id: "offer-6",
    shareId: "offer-geroskipou-sea-villas",
    mainImage: "/images/offers/offer-6/main.jpg",
    images: [
      "/images/offers/offer-6/main.jpg",
      "/images/offers/offer-6/1-v2.jpg",
      "/images/offers/offer-6/2-v2.jpg",
      "/images/offers/offer-6/3-v2.jpg",
      "/images/offers/offer-6/4-v2.jpg",
      "/images/offers/offer-6/5-v2.jpg",
      "/images/offers/offer-6/6.jpg",
    ],
    content: {
      pl: {
        title: "Luksusowe wille przy samym morzu",
        location: "Pafos, Geroskipou",
        type: "Willa",
        bedrooms: "2",
        area: "100 m²",
        price: "Od 690 000 €",
        description: [
          "Wille dwupokojowe o metrażu 100 m² + działka od 165 m² w cenie od 690 000 Euro.",
          "Położona tuż przy malowniczym wybrzeżu Geroskipou w Pafos, ta ekskluzywna, zamknięta inwestycja oferuje wyjątkowe połączenie nowoczesnej architektury, komfortu i prestiżowej lokalizacji.",
          "Kompleks obejmuje 17 eleganckich willi z dwiema sypialniami, dostępnych w zabudowie wolnostojącej oraz bliźniaczej, zaprojektowanych zgodnie z najwyższymi standardami jakości.",
          "Mieszkańcy mogą korzystać z dużego wspólnego basenu, starannie zagospodarowanych terenów zielonych oraz bezpiecznego, prywatnego otoczenia.",
          "Duże przeszklenia, wysokiej jakości wykończenia i nowoczesne rozwiązania architektoniczne tworzą przestrzeń idealną zarówno do codziennego życia, jak i wypoczynku.",
          "Doskonała lokalizacja zapewnia szybki dostęp do plaży, restauracji, sklepów, lotniska oraz najważniejszych atrakcji Pafos.",
          "To idealna propozycja zarówno dla osób poszukujących luksusowego domu nad morzem, jak i dla inwestorów zainteresowanych nieruchomością o wysokim potencjale wzrostu wartości.",
        ],
      },
      en: {
        title: "Luxury Villas Right by the Sea",
        location: "Paphos, Geroskipou",
        type: "Villa",
        bedrooms: "2",
        area: "100 m²",
        price: "From €690,000",
        description: [
          "Two-bedroom villas of 100 m² + plot from 165 m² from €690,000.",
          "Located right by the picturesque Geroskipou coastline in Paphos, this exclusive gated development offers a unique combination of modern architecture, comfort and a prestigious location.",
          "The complex includes 17 elegant two-bedroom villas, available as detached and semi-detached homes, designed to the highest quality standards.",
          "Residents can enjoy a large communal swimming pool, carefully landscaped green areas and a safe, private environment.",
          "Large glass openings, high-quality finishes and modern architectural solutions create a space ideal both for everyday living and relaxation.",
          "The excellent location provides quick access to the beach, restaurants, shops, the airport and the main attractions of Paphos.",
          "It is an ideal choice both for those looking for a luxury home by the sea and for investors interested in a property with strong potential for value growth.",
        ],
      },
    },
  },
];

export function getLocalizedOffers(language: OfferLanguage): OfferView[] {
  return offers.map(({ content, ...offer }) => ({
    ...offer,
    ...content[language],
  }));
}
